### ISSUE TITLE
"تسجيل الدخول" button does nothing in the page following signup

### ISSUE THREAD

**Issue by Youssefares** [TarekAlQaddy/egsl-website-frontend#25]
![image](https://user-images.githubusercontent.com/16102387/58201986-bef3b900-7cd6-11e9-8b22-31ff13eb2bc8.png)

I notice it's disabled. Is that deliberate or just because it happens to be the same front-end route. Don't we think it should take the user back to login form?

**Comment by TarekAlQaddy** [comment]
@Youssefares yes it looks like that because it is the same route you are in login page and `تسجيل الدخول` is not disabled it is activated, when do you think we should bring back the form? I believe if you navigate to different route and got back to `/login` you'll see the form again

**Comment by Youssefares** [comment]
Can we at least insert a button that sends you back to the login form?

**Comment by TarekAlQaddy** [comment]
done here https://github.com/TarekAlQaddy/egsl-website-frontend/commit/a0981f9d96d352cbc351c507c361b00a1b7183b0
