### ISSUE TITLE
Users who signed in via a provider (fb, google) should not have 'edit password' button 

### ISSUE THREAD

**Issue by TarekAlQaddy** [TarekAlQaddy/egsl-website-frontend#28]

**Comment by TarekAlQaddy** [comment]
@yara11 we need a way to know users who signed in via providers, any suggestions?

**Comment by yara11** [comment]
There's a "provider" attribute in the user model, we could modify the user serializer to include it in your user response.

**Comment by TarekAlQaddy** [comment]
@yara11 ok looks good please let me know when it is done

**Comment by TarekAlQaddy** [comment]
Done in https://github.com/TarekAlQaddy/egsl-website-frontend/commit/ff0b0bbe94959ee675aff7c0ab63ed5f3efbbece
